window.FullScreenMap = function({ title = 'Live Safety Map', activeScenario, riskData, currentPos, journeyState, safeBeacon, onBack, onTriggerSos }) {
  const [focused, setFocused] = React.useState(0);
  const [leftOpen, setLeftOpen] = React.useState(true);
  const [rightOpen, setRightOpen] = React.useState(true);
  const emergency = riskData.level.key === 'EMERGENCY';
  return <section className="srg-full-map-page"><div className="srg-page-heading"><button className="srg-btn srg-btn-outline srg-btn-sm" onClick={onBack}>← Back</button><div><p>LIVE MONITORING</p><h1>{title}</h1></div><button className="srg-btn srg-btn-primary srg-btn-sm" onClick={() => setFocused(x => x + 1)}>◎ Focus User</button></div><div className="srg-full-map-canvas"><window.InteractiveMap mapId={'full-map-' + focused} routeWaypoints={activeScenario.routeWaypoints} corridorWidthMeters={activeScenario.corridorWidthMeters} currentPos={currentPos} travelerName={activeScenario.travelerName} travelerAvatar={activeScenario.avatar} safetyLevel={riskData.level.key} isDeviation={riskData.distanceOffCorridor > 0} originName={activeScenario.originName} destinationName={activeScenario.destinationName} />
    <aside className={'srg-map-float srg-map-float-left ' + (!leftOpen ? 'collapsed' : '')}><button className="srg-map-collapse" onClick={() => setLeftOpen(!leftOpen)}>{leftOpen ? '‹' : '›'}</button>{leftOpen && <><p className="srg-float-label">ACTIVE JOURNEYS</p><button className="srg-map-user active" onClick={() => setFocused(x => x + 1)}><span>{activeScenario.avatar}</span><div><b>{activeScenario.travelerName}</b><small>{activeScenario.routeName}</small></div><i style={{background:riskData.level.color}}></i></button><div className="srg-map-user"><span>🛡️</span><div><b>Safe corridor</b><small>{activeScenario.corridorWidthMeters}m protection buffer</small></div></div><p className="srg-float-foot">✓ Trusted safe spots and local helper zones visible on this map.</p></>}</aside>
    <aside className={'srg-map-float srg-map-float-right ' + (!rightOpen ? 'collapsed' : '')}><button className="srg-map-collapse" onClick={() => setRightOpen(!rightOpen)}>{rightOpen ? '›' : '‹'}</button>{rightOpen && <><p className="srg-float-label">SELECTED USER</p><h2>{activeScenario.travelerName}</h2><div className="srg-map-score"><b style={{color:riskData.level.color}}>{riskData.score}</b><span>{riskData.level.label}</span></div><dl><div><dt>Network</dt><dd>Strong · 5G</dd></div><div><dt>Safe Beacon</dt><dd>{safeBeacon ? 'Saved' : 'Ready'}</dd></div><div><dt>Route status</dt><dd>{journeyState.stage.replaceAll('_',' ')}</dd></div></dl>{emergency ? <span className="srg-map-emergency">Emergency active</span> : <button className="srg-btn srg-btn-emergency srg-btn-sm" onClick={() => onTriggerSos('MAP_EMERGENCY_ACTION')}>Emergency SOS</button>}</>}</aside>
    <div className="srg-map-bottom"><span><i className="route"></i> Approved route</span><span><i className="corridor"></i> Geofence corridor</span><span><i className="safe"></i> Trusted safe spot</span><span><i className="alert"></i> Deviation / emergency</span></div>
  </div></section>;
};
