window.RoleFeaturePage = function({ tool, roleId, activeScenario, riskData, safeBeacon, timeline, onBack, onOpen }) {
  const pages = {
    'tourist-home':['Tourist Home','Plan a confident trip with safety intelligence built around your route.','🧳'], 'route-safety':['Route Safety Intelligence','Review route conditions, coverage, and proactive safety guidance.','◈'], 'guardian-home':['Guardian Home','A focused view of your traveler’s current journey and safety state.','👨‍👩‍👧'], 'safe-beacon':['Safe Beacon Mode','Save a last-known safe location when connectivity is limited.','◈'], 'org-home':['Organization Home','A concise operational overview for student and group safety.','🏢'], 'org-reports':['Safety Reports','Review evidence and export a clear journey summary.','◷'], 'admin-users':['User Management','Manage monitored users, roles, and route assignments.','♙'], 'local-help-monitor':['Local Help Monitor','Review simulated local-help requests and support availability.','🤝'], 'helper-verification':['Helper Verification','Verify trusted local helpers before they become visible to travelers.','✓'], settings:['Settings','Choose notification and accessibility preferences for this workspace.','⚙']
  };
  if (tool === 'trusted-safe-spots') return <section className="srg-feature-page"><div className="srg-page-heading"><button className="srg-btn srg-btn-outline srg-btn-sm" onClick={onBack}>← Back</button><div><p>SAFETY LOCATIONS</p><h1>Trusted Safe Spots</h1></div></div><window.TrustedSafeSpots riskData={riskData} /></section>;
  if (tool === 'journey-timeline') return <section className="srg-feature-page"><div className="srg-page-heading"><button className="srg-btn srg-btn-outline srg-btn-sm" onClick={onBack}>← Back</button><div><p>JOURNEY EVIDENCE</p><h1>Journey Evidence Timeline</h1></div></div><window.JourneyTimeline timeline={timeline} activeScenario={activeScenario} safeBeacon={safeBeacon} /></section>;
  const [title, description, icon] = pages[tool] || ['Workspace Page','This focused safety tool is ready for your selected role.','🛡️'];
  return <section className="srg-feature-page"><div className="srg-page-heading"><button className="srg-btn srg-btn-outline srg-btn-sm" onClick={onBack}>← Back</button><div><p>{roleId.toUpperCase()} WORKSPACE</p><h1>{title}</h1></div></div><div className="srg-purpose-card"><span>{icon}</span><div><h2>{title}</h2><p>{description}</p><p className="srg-purpose-note">Active traveler: <b>{activeScenario.travelerName}</b> · Safety score <b>{riskData.score}/100</b></p></div></div>{tool === 'safe-beacon' && <div className="srg-empty-state"><b>{safeBeacon ? 'Safe Beacon available' : 'No Safe Beacon saved yet'}</b><p>{safeBeacon ? `Last saved at ${new Date(safeBeacon.timestamp).toLocaleTimeString()}.` : 'When connectivity becomes limited, the app will store the last known safe location.'}</p></div>}{tool === 'admin-users' && <div className="srg-empty-state"><b>User directory</b><p>Use the profile selector to view the active traveler and assign an approved route.</p><button className="srg-btn srg-btn-primary srg-btn-sm" onClick={() => onOpen('admin-full-map')}>Open monitoring map</button></div>}{tool === 'route-safety' && <div className="srg-empty-state"><b>Route intelligence is available</b><p>Open Explore Safely for weather, connectivity, and official advisory details.</p><button className="srg-btn srg-btn-primary srg-btn-sm" onClick={() => onOpen('explore-safely')}>Open route intelligence</button></div>}</section>;
};
