window.RoleNavigation = function({ roleId, activeTool, onNavigate, onSwitchRole, onLogout, profileName }) {
  const menus = {
    tourist: [['tourist-home','⌂','Tourist Home'],['explore-safely','🧭','Explore Safely'],['route-safety','◈','Route Safety Intelligence'],['community-reviews','★','Community Reviews'],['local-help','🤝','Local Help Network'],['trusted-safe-spots','⌖','Trusted Safe Spots'],['tourist-journey','🗺','My Safe Journey'],['tourist-sos','🚨','Emergency SOS']],
    parent: [['guardian-home','⌂','Guardian Home'],['live-map','◉','Live Map Monitor'],['traveler-status','◌','Child / User Status'],['alerts-feed','🔔','Route Deviation Alerts'],['guardian-contacts','☎','Emergency Contacts'],['journey-timeline','◷','Journey Evidence Timeline'],['safe-beacon','◈','Safe Beacon Updates']],
    traveler: [['traveler-home','⌂','My Journey'],['traveler-live-map','◉','Full-Screen Live Map'],['trusted-safe-spots','⌖','Trusted Safe Spots'],['safe-beacon','◈','Safe Beacon Mode'],['traveler-checkin','✓','Check-in Status'],['traveler-sos','🚨','Emergency SOS']],
    organization: [['org-home','⌂','Organization Home'],['org-monitor','◉','Student / Group Monitor'],['org-full-map','⌖','Full-Screen Map'],['org-routes','▱','Route Management'],['org-incident-log','🔔','Alert Centre'],['org-contacts','☎','Trusted Contacts'],['org-reports','◷','Safety Reports']],
    admin: [['admin-overview','⌂','Admin Overview'],['admin-full-map','◉','Monitoring Map'],['admin-users','♙','User Management'],['admin-routes','▱','Routes & Geofences'],['alerts-feed','🔔','Emergency Alert Centre'],['local-help-monitor','🤝','Local Help Monitor'],['helper-verification','✓','Helper Verification'],['journey-timeline','◷','Journey Evidence'],['admin-ai-engine','✦','AI Risk Engine']]
  };
  const role = (window.SRG_DATA.roles || []).find(item => item.id === roleId) || { icon:'🛡️', title:'Workspace' };
  const [profileOpen, setProfileOpen] = React.useState(false);
  return <><aside className="srg-role-sidebar"><div className="srg-side-brand"><span>🛡️</span><b>SafeRoute</b></div><div className="srg-side-role"><span>{role.icon}</span><div><small>CURRENT WORKSPACE</small><b>{role.title}</b></div></div><nav>{menus[roleId].map(([id,icon,label]) => <button key={id} className={activeTool === id ? 'active' : ''} onClick={() => onNavigate(id)} title={label}><span>{icon}</span><b>{label}</b></button>)}</nav><div className="srg-side-profile"><button className="srg-profile-trigger" onClick={() => setProfileOpen(!profileOpen)}><span>👤</span><div><b>{profileName}</b><small>{role.title}</small></div><i>⌄</i></button>{profileOpen && <div className="srg-profile-menu"><button onClick={onSwitchRole}>⇄ Switch role</button><button onClick={() => onNavigate('settings')}>⚙ Settings</button><button onClick={onLogout}>↪ Log out</button></div>}</div></aside><nav className="srg-mobile-nav">{menus[roleId].slice(0,5).map(([id,icon,label]) => <button key={id} className={activeTool === id ? 'active' : ''} onClick={() => onNavigate(id)}><span>{icon}</span><small>{label.split(' ')[0]}</small></button>)}<button onClick={onSwitchRole}><span>⇄</span><small>Roles</small></button></nav></>;
};
